# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
# edited for code nebula
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
    displayName: 'Install Node.js'  
    
- script: |
    npm install
    npm run build
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: false

# Publish build artifacts to Azure Artifacts/TFS
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/build'
    artifactName: 'codenebulaBackend'
    
# Publish build artifacts to Azure Artifacts/TFS
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/deploy-backend.sh'
    artifactName: 'deploy-backend'
    
